(() => {
  'use strict';
  const variants = [
    { id: 'industrial', number: '01', name: 'Сила в работе', style: 'Индустриальный', description: 'Графит, сигнальный оранжевый и выразительная типографика.', title: 'Большой технике.<br><em>Большой опыт.</em>', intro: 'Диагностика, обслуживание и ремонт грузовиков, прицепов и спецтехники в Пскове. Работаем с 2008 года.', image: 'truck.jpg', label: 'Грузовой сервис / Псков' },
    { id: 'nordic', number: '02', name: 'Точный подход', style: 'Светлый', description: 'Чистая композиция, глубокий синий и внимание к деталям.', title: 'Ваш транспорт.<br><em>Наша работа.</em>', intro: 'От планового ТО до сложного ремонта. Помогаем поддерживать в рабочем состоянии грузовые и легковые автомобили, автобусы и спецтехнику.', image: 'truck.jpg', label: 'ТракСервис. С 2008 года' },
    { id: 'graphite', number: '03', name: 'Снова в рейс', style: 'Тёмный', description: 'Крупная фотография, глубокий чёрный и лаконичные акценты.', title: 'Техника должна<br><em>работать.</em>', intro: 'А мы — заботиться о её исправности. Комплексное обслуживание и ремонт коммерческого транспорта в Пскове.', image: 'road.jpg', label: 'Ремонт. Обслуживание. Движение.' },
    { id: 'technical', number: '04', name: 'Всё под контролем', style: 'Технический', description: 'Чёткая сетка, холодный зелёный и подробная подача услуг.', title: 'От диагностики<br><em>до результата.</em>', intro: 'Ходовая, трансмиссия, тормоза, плановое ТО. Подбираем работы под состояние и задачи вашей техники.', image: 'workshop.jpg', label: 'Сервис полного цикла / 60 RUS' }
  ];
  const services = [
    ['Диагностика и ТО', 'Компьютерная диагностика и плановое техническое обслуживание. Замена расходных материалов и комплектующих.', '01'],
    ['Ходовая часть', 'Ремонт подвески и ходовой части. Регулировка развала-схождения.', '02'],
    ['Трансмиссия', 'Диагностика и ремонт трансмиссии. Перечень работ согласуем после осмотра техники.', '03'],
    ['Тормозная система', 'Диагностика, обслуживание и ремонт тормозной системы.', '04'],
    ['Прицепы и полуприцепы', 'Диагностика и ремонт прицепной техники, обслуживание её узлов и систем.', '05'],
    ['Газосварочные работы', 'Восстановительные и газосварочные работы. Возможность ремонта и сроки уточним при обращении.', '06']
  ];
  const map = 'https://yandex.ru/maps/org/trakservis/159473227777/';
  const logo = '<span class="logo-mark">Т<span>С</span></span><span class="logo-text">ТракСервис<small>РЕМОНТ И ОБСЛУЖИВАНИЕ</small></span>';
  const app = document.getElementById('app');
  const designHref = id => `site.html?design=${id}`;
  if (document.body.classList.contains('showcase')) {
    app.innerHTML = `<div class="gallery-wrap"><header class="gallery-header"><a class="logo" href="index.html">${logo}</a><span>Псков · с 2008 года</span></header>
      <section class="gallery-intro"><p class="eyebrow">Персональная подборка / ТракСервис</p><h1>Один сервис.<br><span>Четыре характера.</span></h1><p>Выберите, каким будет ваш сайт.</p></section>
      <div class="design-grid">${variants.map(v => `<a class="design-card preview-${v.id}" href="${designHref(v.id)}"><div class="design-art"><img src="assets/${v.image}" alt="Грузовая техника — ${v.style.toLowerCase()} вариант сайта" loading="eager"><div class="mini-brand">ТРАКСЕРВИС <span>/${v.number}</span></div><div class="mini-heading">${v.title}</div><span class="mini-button">Записаться на ремонт ↗</span></div><div class="design-info"><span class="design-number">${v.number}</span><div><p>${v.style}</p><h2>${v.name}</h2><span>${v.description}</span></div><b aria-hidden="true">↗</b></div></a>`).join('')}</div>
      <footer class="gallery-footer"><p>В каждом варианте: услуги, информация о сервисе и контакты.</p><a href="${designHref('industrial')}">Начать с первого варианта ↗</a></footer></div>`;
    return;
  }
  const requested = new URLSearchParams(location.search).get('design');
  const v = variants.find(item => item.id === requested) || variants[0];
  document.body.className = `theme-${v.id}`;
  document.title = `ТракСервис — ${v.name} | Ремонт грузовиков в Пскове`;
  app.innerHTML = `
    <div class="design-bar"><a href="index.html">← Все варианты</a><nav aria-label="Вариант дизайна">${variants.map(item => `<a href="${designHref(item.id)}" ${item.id === v.id ? 'aria-current="page"' : ''}><span>${item.number}</span> ${item.style}</a>`).join('')}</nav><span class="demo-label">Демо сайта</span></div>
    <div class="topline"><div class="container"><span>Псков, Леона Поземского, 121к1</span><span>Пн–Пт · 09:00–18:00</span></div></div>
    <header class="header"><div class="container header-inner"><a class="logo" href="#top" aria-label="ТракСервис — в начало">${logo}</a><button class="menu-toggle" type="button" aria-label="Открыть меню" aria-expanded="false" aria-controls="navigation">Меню <span>☰</span></button><nav class="main-nav" id="navigation" aria-label="Основная навигация"><a href="#services">Услуги</a><a href="#vehicles">Техника</a><a href="#about">О сервисе</a><a href="#contacts">Контакты</a></nav><a class="header-phone" href="tel:+79319017477">+7 (931) 901-74-77<small>Запись на ремонт</small></a></div></header>
    <main id="main"><section class="hero" id="top"><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow">${v.label}</p><h1>${v.title}</h1><p class="hero-description">${v.intro}</p><div class="actions"><a class="button primary" href="tel:+79319017477">Записаться на ремонт <span>↗</span></a><a class="button secondary" href="#services">Наши услуги <span>↓</span></a></div><div class="hero-note"><span>2008</span><p>год начала работы<br>сервиса</p></div></div><figure class="hero-media"><img src="assets/${v.image}" alt="Грузовой автомобиль: ремонт и обслуживание в ТракСервис" fetchpriority="high"><figcaption><span>ТРАКСЕРВИС / ПСКОВ</span><b>Готовы к большой работе.</b></figcaption></figure><span class="hero-index" aria-hidden="true">ТС / 60</span></div></section>
    <div class="capabilities"><div class="container"><span>Грузовые автомобили</span><span>Прицепы</span><span>Автобусы</span><span>Спецтехника</span></div></div>
    <section class="section services" id="services"><div class="container"><div class="section-heading"><div><p class="eyebrow">01 / Что мы делаем</p><h2>От планового ТО<br>до сложного ремонта.</h2></div><p>Полный цикл обслуживания техники.<br>Состав работ, стоимость и сроки<br>согласуем до начала ремонта.</p></div><div class="service-grid">${services.map(s => `<article class="service-card"><span class="service-index">${s[2]}</span><h3>${s[0]}</h3><p>${s[1]}</p><a href="tel:+79319017477" aria-label="Уточнить стоимость: ${s[0]}">Уточнить стоимость <span>↗</span></a></article>`).join('')}</div></div></section>
    <section class="section vehicles" id="vehicles"><div class="container vehicle-grid"><div><p class="eyebrow">02 / С чем работаем</p><h2>Разная техника.<br>Единый подход.</h2><p class="section-description">Обслуживаем технику китайских, корейских, японских, американских и европейских брендов.</p><a class="text-link" href="https://vk.ru/truck60" target="_blank" rel="noopener noreferrer">Больше о сервисе во ВКонтакте ↗</a></div><div class="vehicle-list">${[['Грузовики и прицепы','Тягачи, грузовые автомобили, прицепная техника'],['Автобусы и микроавтобусы','Пассажирский и коммерческий транспорт'],['Спецтехника','Обслуживание и ремонт специальной техники'],['Легковые и малотоннажные','Личные автомобили и транспорт для бизнеса']].map((item,i) => `<article><span>0${i+1}</span><div><h3>${item[0]}</h3><p>${item[1]}</p></div></article>`).join('')}</div></div></section>
    <section class="section about" id="about"><div class="container about-grid"><figure class="about-image"><img src="assets/repair.jpg" alt="Ремонт и обслуживание грузовой техники" loading="lazy"><figcaption>ТракСервис · Работаем с 2008 года</figcaption></figure><div class="about-copy"><p class="eyebrow">03 / О сервисе</p><h2>Знаем технику.<br>Ценим ваше время.</h2><p>«ТракСервис» — команда специалистов по обслуживанию и ремонту транспорта в Пскове. Берёмся за задачи от компьютерной диагностики до сложного ремонта.</p><div class="principles"><div><b>Комплексный подход</b><p>Диагностика, техническое обслуживание и ремонт в одном сервисе.</p></div><div><b>Согласованные сроки</b><p>Обсуждаем объём работ и время выполнения, чтобы вы могли планировать поездки и рейсы.</p></div></div><a class="text-link" href="${map}reviews/" target="_blank" rel="noopener noreferrer">Отзывы клиентов на Яндекс Картах ↗</a></div></div></section>
    <section class="section process"><div class="container"><div class="section-heading"><div><p class="eyebrow">04 / Порядок работы</p><h2>Понятно на каждом этапе.</h2></div></div><div class="process-grid">${[['Свяжитесь с нами','Позвоните или напишите в группу ВКонтакте.'],['Расскажите о технике','Укажите марку, модель и что требует внимания.'],['Согласуйте работы','Уточните время визита, диагностику и условия ремонта.'],['Приезжайте в сервис','Псков, ул. Леона Поземского, 121, корпус 1.']].map((s,i)=>`<article><span>0${i+1}</span><h3>${s[0]}</h3><p>${s[1]}</p></article>`).join('')}</div></div></section>
    <section class="contacts section" id="contacts"><div class="container contact-grid"><div><p class="eyebrow">05 / На связи</p><h2>Обсудим<br>вашу задачу.</h2><p>Подскажем по услугам и согласуем время визита.</p><a class="contact-phone" href="tel:+79319017477">+7 (931) 901-74-77</a><a class="contact-mail" href="mailto:trakservis-psk@mail.ru">trakservis-psk@mail.ru</a><div class="actions"><a class="button primary" href="tel:+79319017477">Позвонить <span>↗</span></a><a class="button secondary" href="https://vk.ru/truck60" target="_blank" rel="noopener noreferrer">ВКонтакте <span>↗</span></a></div></div><div class="address-card"><span class="address-label">ТРАКСЕРВИС / 60</span><h3>Псков</h3><p>ул. Леона Поземского, 121,<br>корпус 1</p><div class="hours"><span>Понедельник — пятница</span><b>09:00–18:00</b></div><a class="button map-button" href="${map}" target="_blank" rel="noopener noreferrer">Открыть на Яндекс Картах <span>↗</span></a></div></div></section></main>
    <footer class="footer"><div class="container"><a class="logo" href="#top">${logo}</a><p>ТракСервис · Псков<br>Ремонт и обслуживание транспорта</p><a href="index.html">Все варианты сайта ↗</a></div></footer><a class="mobile-call" href="tel:+79319017477">Позвонить в ТракСервис ↗</a>`;
  const toggle = document.querySelector('.menu-toggle');
  const nav = document.querySelector('.main-nav');
  const closeMenu = () => { toggle.setAttribute('aria-expanded', 'false'); nav.classList.remove('is-open'); };
  toggle.addEventListener('click', () => { const open = toggle.getAttribute('aria-expanded') !== 'true'; toggle.setAttribute('aria-expanded', String(open)); nav.classList.toggle('is-open', open); });
  nav.querySelectorAll('a').forEach(a => a.addEventListener('click', closeMenu));
  document.addEventListener('keydown', e => { if (e.key === 'Escape') closeMenu(); });
})();
